# Site settings
title: walsh9.github.io
email: walsh9@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://walsh9.github.io" # the base hostname & protocol for your site
twitter_username: walsh9dbc
github_username:  walsh9

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  enable_coderay: false
permalink: blog/:categories/:year/:month/:day/:title
collections:
  projects: