# Site settings
title: walsh9.net
email: walsh9@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://walsh9.net" # the base hostname & protocol for your site
github_username:  walsh9
linkedin_url:  matthewcwalsh
google_plus_username: ~
twitter_username: ~

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  enable_coderay: false
paginate: 5
paginate_path: "/:num/"
permalink: ":categories/:title"
collections:
  projects:

gems:
- jekyll-redirect-from